eaf_temp:
  path: ../data/raw/eaf_temp.csv
  parse_dates: ["DATETIME"]
  description: "Temperature and oxidation measurements in EAF (time-series)."

eaf_final_chemical:
  path: ../data/raw/eaf_final_chemical_measurements.csv
  parse_dates: ["DATETIME"]
  description: "Final chemical composition measurements in EAF."

basket_charged:
  path: ../data/raw/basket_charged.csv
  parse_dates: ["DATETIME"]
  description: "Loading furnace from the basket."

eaf_added:
  path: ../data/raw/eaf_added_materials.csv
  parse_dates: ["DATETIME"]
  description: "Additional charge and loading of furnace."

eaf_transformer:
  path: ../data/raw/eaf_transformer.csv
  parse_dates: ["STARTTIME"]
  description: "EAF transformer stage operations and power."

inj_mat:
  path: ../data/raw/inj_mat.csv
  parse_dates: ["REVTIME"]
  description: "Usage of injected carbon in EAF (cumulative counters)."

eaf_gaslance:
  path: ../data/raw/eaf_gaslance_mat.csv
  parse_dates: ["REVTIME"]
  description: "Gas and oxygen usage in EAF (cumulative counters)."

ferro:
  path: ../data/raw/ferro.csv
  parse_dates: []
  description: "Materials description with chemical element contents (composition table)."

  # All the datasets below are related to the ladle furnace (LF) stage, which is not the focus of this project. They are included here for completeness and potential future use.

  # ladle_tapping:
  # path: ../data/raw/ladle_tapping.csv
  # parse_dates: ["DATETIME"]
  # description: "Additions at EAF tapping."

  # lf_added:
  # path: ../data/raw/lf_added_materials.csv
  # parse_dates: ["DATETIME"]
  # description: "Additions to ladle furnace before initial chemical measurement."

  # lf_initial_chemical:
  # path: ../data/raw/lf_initial_chemical_measurements.csv
  # parse_dates: ["DATETIME"]
  # description: "Initial chemical measurements at ladle furnace."